---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: lint
    image: python:alpine
    pull: always
    commands:
      - apk add --no-cache gcc libc-dev make
      - pip install --break-system-packages -e '.[lint]'
      - black --check .
      - isort --check .
      - pyupgrade --py312-plus $(find drone_notify -name '*.py')
      - pylint drone_notify
      - mypy drone_notify

  - name: test
    image: python:alpine
    pull: always
    commands:
      - apk add --no-cache gcc libc-dev make
      - pip install --break-system-packages -e '.[test]'
      - pytest

  - name: build
    image: spritsail/docker-build
    pull: always

  - name: publish
    image: spritsail/docker-publish
    pull: always
    settings:
      repo: spritsail/drone-notify
      tags:
        - latest
        - "%label org.label-schema.version"
      login: {from_secret: docker_login}
    depends_on:
      - build
      - lint
      - test
    when:
      branch:
        - master
      event:
        - push

  - name: update-dockerhub-readme
    image: jlesage/drone-push-readme
    pull: always
    settings:
      username: {from_secret: docker_username}
      password: {from_secret: docker_password}
      repo: spritsail/drone-notify
    depends_on:
      - publish
    when:
      branch:
        - master
      event:
        - push
---
kind: signature
hmac: 01ed4509e0bfd930ad462a83148a9530371cee10136f61b76887d008c6680e58

...
