pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: notify-dev

  test:
    image: notify-dev
    method: GET
    webhook_url: ${CI_SYSTEM_LINK}/api/badges/${DRONE_REPO}/status.svg

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: notify-dev
    repo: spritsail/notify

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
