---
kind: pipeline
name: test

steps:
  - name: go test
    image: golang:alpine
    pull: always
    commands:
      - go test -tags goolm ./...

---
kind: pipeline
name: default

depends_on:
  - test

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: spritsail/docker-build
    pull: always

  - name: publish-spritsail
    pull: always
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      registry: registry.spritsail.io
      login: { from_secret: spritsail_login }
      repo: spritsail/drone-notify
      tags:
        - go
      delete: no # so we can push to dockerhub+ghcr
    depends_on:
      - build
    when:
      branch:
        - go
      event:
        - push

  - name: publish-ghcr
    pull: never
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      registry: ghcr.io
      login: { from_secret: ghcr_login }
      repo: spritsail/drone-notify
      tags:
        - latest
      delete: no # so we can push to dockerhub
    depends_on:
      - build
    when:
      branch:
        - go
      event:
        - push

  - name: publish-dockerhub
    pull: never
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      login: { from_secret: docker_login }
      repo: spritsail/drone-notify
      tags:
        - go
    depends_on:
      - build
    when:
      branch:
        - go
      event:
        - push

  - name: update-dockerhub-readme
    image: jlesage/drone-push-readme
    pull: always
    settings:
      username: { from_secret: docker_username }
      password: { from_secret: docker_password }
      repo: spritsail/drone-notify
    depends_on:
      - publish-dockerhub
    when:
      branch:
        - master
      event:
        - push
---
kind: signature
hmac: da7152673b184ccf59fc4a5b14a856154f2cae995bff91f6f9a3a64e0123667c

...
