[project]
name = "drone-notify"
version = "1.3"
dependencies = [
  "aiohttp>=3.8"
]

[project.optional-dependencies]
lint = [
  "black",
  "isort",
  "mypy",
  "pylint",
  "pyupgrade",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
fast = true
line-length = 100

[tool.isort]
profile = "black"

[tool.pylint.'messages control']
enable = "all"
disable = [
  "fixme",
  # Several vars in __main__.py need refactoring
  "used-before-assignment",
]

[tool.mypy]
strict = true
